PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Controllers/LibroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace PL.Controllers
{
    public class LibroController : Controller
    {
        // GET: Libro
        public ActionResult GetAll()
        {
            var serv = new LibroServiceReference.LibroServiceClient();
            var resultado = serv.GetAll();
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();
            foreach (var item in resultado)
            {
                ML.Libro libro = new ML.Libro();
                libro.IdLibro = item.IdLibro;
                libro.Nombre = item.Nombre;
                libro.FechaPublicacion = item.FechaPublicacion;
                libro.NumeroPaginas = item.NumeroPaginas;
                libro.Autor = new ML.Autor();
                libro.Autor.IdAutor = item.IdAutor;
                libro.Autor.NombreCompleto = item.AutorNombre;

                result.Objects.Add(libro);
            }
            return View(result);
        }//GetAll

        [HttpGet]
        public ActionResult Form(int? idLibro)
        {
            ML.Libro libro = new ML.Libro();
            libro.Autor = new ML.Autor();
            ML.Result result = BL.Autor.GetAll();
            libro.Autor.Autores = result.Objects;
            if (idLibro == null)
            {
                //FormVacio
                return View(libro);
            }
            else
            {
                //GetById
                var serv = new LibroServiceReference.LibroServiceClient();
                var resultado = serv.GetById(idLibro.Value);
                string f = resultado.FechaPublicacion;
                string dd = f.Substring(0, 2);
                string MM = f.Substring(3, 2);
                string yyyy = f.Substring(6, 4);
                string fecha = MM + "-" + dd + "-" + yyyy;
                
                libro.IdLibro = resultado.IdLibro;
                libro.Nombre = resultado.Nombre;
                libro.FechaPublicacion = fecha;
                libro.NumeroPaginas = resultado.NumeroPaginas;
                libro.Autor.IdAutor = resultado.IdAutor;
                //libro.Autor.NombreCompleto = resultado.AutorNombre;

                return View(libro);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Libro libro)
        {
            if (libro.IdLibro == 0)
            {
                var serv = new LibroServiceReference.LibroServiceClient();
                var obj = new SL.Libro
                {
                    Nombre = libro.Nombre,
                    FechaPublicacion = libro.FechaPublicacion,
                    NumeroPaginas = libro.NumeroPaginas,
                    IdAutor = libro.Autor.IdAutor
                };
                bool r = serv.Add(obj);

                if (r)
                {
                    ViewBag.Message = "Registro almacenado exitosamente";
                }
                else
                {
                    ViewBag.Message = "Error al almacenar el registro";
                }
                return View("Modal");
            }
            else
            {
                //Update
                var serv = new LibroServiceReference.LibroServiceClient();
                var obj = new SL.Libro
                {
                    IdLibro = libro.IdLibro,
                    Nombre = libro.Nombre,
                    FechaPublicacion = libro.FechaPublicacion,
                    NumeroPaginas = libro.NumeroPaginas,
                    IdAutor = libro.Autor.IdAutor
                };
                bool r = serv.Update(obj);

                if (r)
                {
                    ViewBag.Message = "Registro actualizado correctamente";
                }
                else
                {
                    ViewBag.Message = "Error al editar el registro";
                }
                return View("Modal");
            }            
        }//Form(post)

        public ActionResult Delete(int idLibro)
        {
            var serv = new LibroServiceReference.LibroServiceClient();
            bool r = serv.Delete(idLibro);

            if (r)
            {
                ViewBag.Message = "Registro eliminado correctamente";
            }
            else
            {
                ViewBag.Message = "Error al eliminar";
            }
            return View("Modal");
        }
    }
}

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PL/Views/Libro/Form.cshtml
@model ML.Libro
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h2>Registrar un nuevo libro</h2>
    </div>
    <hr />

    @using (Html.BeginForm("Form", "Libro", FormMethod.Post, new { enctype = "multipart/form-data" }))
     {
        @Html.TextBoxFor(model => model.IdLibro, htmlAttributes: new { @class = "visually-hidden" })
        <div class="row">
            <div class="col">
                @Html.LabelFor(model => model.Nombre)
                @Html.TextBoxFor(model => model.Nombre, htmlAttributes: new { @class = "form-control" })
            </div>

            <div class="col">
                @Html.LabelFor(model => model.FechaPublicacion) (MM/DD/AAAA)
                @Html.TextBoxFor(model => model.FechaPublicacion, htmlAttributes: new { @class = "form-control" })
            </div>

            <div class="col">
                @Html.LabelFor(model => model.NumeroPaginas)
                @Html.TextBoxFor(model => model.NumeroPaginas, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="col">
                @Html.LabelFor(model => model.Autor)
                @Html.DropDownListFor(model => model.Autor.IdAutor, 
               new SelectList(Model.Autor.Autores, "IdAutor", "NombreCompleto"),
                            "Selecciona un autor", new { @class = "form-control" })
            </div>
            
        </div>

        <br />
        
        <div class="row">
            <div class="col">
                <input type="submit" value="Guardar" class="btn btn-success"/>
            </div>
            <div class="col" style="text-align:end">
                @Html.ActionLink("Regresar", "GetAll", "Libro", htmlAttributes: new { @class = "btn btn-danger"})
            </div>
        </div>

     }
</div> <!-- container -->

PL/Views/Libro/GetAll.cshtml
@model ML.Result
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col">
            <h2>Libros</h2>
        </div>
        <div class="col" style="text-align:end">
            @Html.ActionLink("Agregar","Form","Libro",htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>
    <hr />

    @if (Model.Objects != null)
    {
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <td>Editar</td>
                    <td class="visually-hidden">IdLibro</td>
                    <td>Titulo</td>
                    <td>Fecha Publicacion</td>
                    <td>Paginas</td>
                    <td>Autor</td>
                    <td>Eliminar</td>
                </tr>
            </thead>
            <tbody>                
                @foreach (ML.Libro libro in Model.Objects)
                {
                    <tr>
                        <td><a class="btn-warning" 
                               href="@Url.Action("Form","Libro", new { idLibro = libro.IdLibro })">Edit</a></td>
                        <td class="visually-hidden">@libro.IdLibro</td>
                        <td>@libro.Nombre</td>
                        <td>@libro.FechaPublicacion</td>
                        <td>@libro.NumeroPaginas</td>
                        <td>@libro.Autor.NombreCompleto </td>
                        <td><a class="btn-danger"
                               href="@Url.Action("Delete","Libro", new { idLibro = libro.IdLibro })">Eliminar</a></td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="alert-danger" role="alert">No hay registros para mostrar</div>
    }
</div> <!-- container -->

PL/Views/Libro/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Libro", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Libros", "GetAll", "Libro", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>